ALTER TYPE "AuditAction" ADD VALUE 'HOMEPAGE_CONTENT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'HOMEPAGE_IMAGE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'HOMEPAGE_CAROUSEL_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'HOMEPAGE_NEWS_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'HOMEPAGE_NEWS_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'HOMEPAGE_NEWS_DELETED';

ALTER TABLE "SiteSettings"
  ADD COLUMN "homepageContent" JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN "homepageNews" JSONB NOT NULL DEFAULT '[]'::jsonb;
